FullScreenShenanigans/FullScreenPokemon

- GameStartr/PixelRendr/PixelRendr.js
also it looks like visualstudio changed some of the spacing
> add (nicer) lazy loading 

- settings/math.js
so now you can choose bulbasaur!
> pokemon -> %%%pokemon%%%

- Source/FullScreenPokemon.d.ts
- Source/FullScreenPokemon.ts
- Source/References/BattleMovr-0.2.0.ts
> Names stored as string[] in ItemsHoldr

- Source/FullScreenPokemon.d.ts
- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
- Source/References/AreaSpawnr-0.2.0.ts
- Source/References/GameStartr-0.2.0.js
- Source/References/GameStartr-0.2.0.ts
- Source/References/MathDecidr-0.2.0.js
- Source/References/MathDecidr-0.2.0.ts
- Source/References/MenuGraphr-0.2.0.ts
- Source/References/UserWrappr-0.2.0.ts
This in addition to a bunch of documentation updates.
> Added Usagehelpr

- Source/FullScreenPokemon.ts
Added documentation for when your character is spotted by another trainer for battle.
> Documented trainer spotted cutscene

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
Documented Functions in the Memory section
> Documenting Functions

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
Documented Functions in Map Entrances section and Miscellaneous Utilities section
> Documented Functions

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
FullScreenPokemon.ts/FullScreenPokemon.js no longer use ensureCorrectCaller
> Removed instances of ensureCorrectCaller

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
animateCharacterSetDirection wasn't properly reacting to the logic of
.right being a mirror of .left.
> Fixed visual direction classes

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
- Source/settings/objects.js
> Add recent documentation additions to master

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
It should return a `Scrollability` value, not a string.
> Updated getScreenScrollability for enum

- Source/FullScreenPokemon.d.ts
- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
- Source/settings/objects.js
Added a CyclingRoad Thing that when stepped on, forces the player to get on the bicycle.
Some comments missing.
Placeholder function for forcing movement.
> Player gets on his bicycle when entering a cycling road tile

- Source/FullScreenPokemon.d.ts
- Source/References/ModAttachr-0.2.2.ts
- Source/settings/menus.js
- Source/settings/mods.ts
- Source/settings/ui.ts
Adds a single "Running Indoors" mod and opens the door for more.
> Initial mods support

- Source/FullScreenPokemon.d.ts
- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
- Source/settings/maps/Viridian City.js
- Source/settings/objects.js
This is from the last PR, it committed and you accepted the PR but I accidentally updated the commit after the you merged the branch and everything went screwy.
> Player gets on bicycle when entering cycling road

- Source/FullScreenPokemon.d.ts
- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
- Source/settings/objects.js
Reverts FullScreenShenanigans/FullScreenPokemon#236
Checks didn't pass
> Revert "Updates from master branch"

- package.json
> Updated package.json to newest packages

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
> Player can't move during battle start animation

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
Comment was copied from Left but not everything was changed
> Changed Descriptions of Up, Down, and Right key presses

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
fix for Player being able to move during the Rival walking to its starter and during ledge hops
> Fix for two bugs (including a fix for #229)

- Source/FullScreenPokemon.d.ts
- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
- Source/References/GameStartr-0.2.0.ts
- Source/settings/mods.js
- Source/settings/mods.ts
- Source/settings/objects.js
Adding state history functionality to non-primitive objects in FSP
> State History

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
adding the note animation for the Growl attack
> Growl animation

- Source/FullScreenPokemon.d.ts
- Source/FullScreenPokemon.ts
> Changing type of opponent in battles to IEnemy

- Source/FullScreenPokemon.d.ts
- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
- Source/settings/groups.js
- Source/settings/maps.js
- Source/settings/maps.ts
> Replacing MapScreener.thingsById with a new GroupHolder group

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
> Fixing scope in activateMenuTriggerer

- Source/FullScreenPokemon.js
- Source/FullScreenPokemon.ts
- Source/References/AudioPlayr-0.2.1.js
- Source/References/AudioPlayr-0.2.1.ts
In addition, also making it so running away from a battle start's the area's theme.
> Fixing "Uncaught Promise" error message from AudioPlayr's `playTheme`

- Source/References/PixelRendr-0.2.0.js
- Source/References/PixelRendr-0.2.0.ts
> Adding the ability to change palettes in PixelRendr

- src/Settings/MapsLibrary/PewterCity.ts
Within PewterCity.ts the badge had been named Brock, it is now name Boulder.
> Changed badge names from name of gym leader to name of actual badge

- src/Cutscenes.ts
- src/Settings/Scenes.ts
Still requires new "sand" sprites
> Implemented Sand Attack Battle Animation

- src/Menus.ts
- src/Settings/Menus.ts
Reshaped Items menu, added use/toss Item menu, fixed Pause menu to
reshape if the Player has a Pokedex. Fixes #361.
> Updated Items menu so that item interaction is possible

- src/Cutscenes.ts
- src/Settings/Scenes.ts
Still requires new "Gust" and "ExplosionRound" sprites
> Implemented Gust Battle Animation

- src/components/cutscenes/IntroCutscene.ts
They weren't large enough, thanks to the removal of unitsize.
> Fixed into's horizontal sliding amounts

- src/docs/Battles.md
> Added brief guide on battles

- test/components/Collisions/isCharacterTouchingCharacter.ts
Nothing yet for tolerance. It's a good start.
> Added brief isCharacterTouchingCharacter tests

- .travis.yml
No before_script installation of gulp
> Updated .travis.yml to be faster

- src/components/battles/Animations.ts
- src/components/battles/animations/Ending.ts
- src/components/battles/selectors/OpponentSelector.ts
- src/components/battles/selectors/PlayerSelector.ts
- src/components/cutscenes/OakIntroRivalLeavesCutscene.ts
Battles weren't properly being marked as complete because the internal stopBattle callback was never being called.
> Correctly piped battle ending animations

- src/components/mods/FSPEventNames.ts
Small implementation specific to FSP
> Added custom EventNames inheritor specific to FSP, Addresses #423

- src/components/constants/Pokemon.ts
- src/components/mods/FSPEventNames.ts
> Adding in structure for evolution data

- src/components/constants/Pokemon.ts
> Changed structure of evolution data to new format

- src/components/Actions.ts
- src/components/Equations.ts
- src/components/Maps.ts
- src/components/Things.ts
- src/components/battles/ActionsOrderer.ts
- src/components/battles/animations/shared/Effects.ts
- src/components/battles/animations/shared/Fainting.ts
- src/settings/Menus.ts
Should fix a number of build issues.
> Touched up some previously null typings

- src/components/Evolution.ts
- src/components/constants/Pokemon.ts
> Added check for evolution

- src/components/Experience.ts
> Added support for experience gain and level ups

- README.md
> Added section markers to README.md

- src/FullScreenPokemon.ts
- src/components/Evolution.ts
- src/components/Experience.ts
- test/components/isEvolved.ts
> Added basic unit tests for evolution

- README.md
- package.json
- src/components/Actions.ts
- src/components/Maps.ts
- src/components/Things.ts
- src/components/actions/Ledges.ts
- src/components/battles/animations/shared/moves/moves/Bubble.ts
- src/components/battles/animations/shared/moves/moves/Growl.ts
- src/components/battles/animations/shared/moves/moves/QuickAttack.ts
- src/components/battles/animations/shared/moves/moves/Scratch.ts
- src/components/cutscenes/IntroCutscene.ts
- src/components/cutscenes/OakIntroCutscene.ts
- src/components/cutscenes/OakParcelDeliveryCutscene.ts
- src/components/cutscenes/PokeCenterCutscene.ts
- src/components/cutscenes/RivalRoute22Cutscene.ts
- src/components/things/names.ts
Added a thingsNames class which allows for this.gameStarter.things.names.x (x being the string literal in variable form) to be used instead of string literals. This allows for easier refractoring
Close #457
> thingsNames class added

- src/components/Mods.ts
- src/components/actions/Grass.ts
- src/components/mods/RandomizeWildPokemonMod.ts
- src/components/things/names.ts
A mod that randomizes wild Pokemon encounters based off of the original Pokemon's type. Also made a bug fix by changing "shadow" to "Shadow" in the names.ts file. Closed #472
> RandomizeWildPokemon Mod

- src/components/Maps.ts
These were never fixed after the unitsize conversion.
Fixes #464.
> Adjusted InvisibleWall offsets to be 32, not 8

- src/components/Menus.ts
* Changed Pokedex menu height to 255
closes #505
> Fixed Pokedex menu height

- src/components/Actions.ts
Had to uncomment a line to get it to work... now you can have conversation with NPCs that have dialogue options and not get stuck
> Fixes dialogues with options

- docs/pokemonCreation.md
* Created documentation for Pokemon Creation.
closes #502
> Pokemon Creation documentation

- src/components/Cutscenes.ts
- src/components/Mods.ts
- src/components/battles/animations/Ending.ts
- src/components/cutscenes/RivalRoute22Cutscene.ts
- src/components/cutscenes/RivalRoute22LeavesCutscene.ts
- src/settings/Scenes.ts
Closes #509
* Rival battle now starts and rival has proper dialogue/walks away.
> Rival route 22 bug fix

- src/components/audio/SoundNames.ts
- src/components/cutscenes/IntroCutscene.ts
The introduction song will play when a player starts a New Game
Fixes #30
> Adding introduction song to the New Game screen

- src/components/Battles.ts
- src/components/battles/animations/Ending.ts
fixes #462 by adding the "ending" theme / original map music as a property of the battle options
> Battle audio fix

- src/components/Experience.ts
- src/components/battles/animations/shared/Fainting.ts
Adds gaining experience to the fainting.ts file.  Also I haven't tested this against real trainers, only wild pokemon.  Fixes #504
> Added experience gain from battles

- src/components/MoveAdder.ts
> Added an API for giving a Pokemon a new move

- src/components/cutscenes/OakIntroPokemonChoiceCutscene.ts
Fixed an issue where talking to a Pokeball before the Professor Oak cutscene would freeze the game.
Fixes #640
> Fixed Oak Cutscene Bug

- src/components/cutscenes/OakIntroPokemonChoiceCutscene.ts
- src/components/menus/Pokemon.ts
> Fixed an issue where a Pokemon's status would not be correctly displayed.

- src/components/MoveAdder.ts
> Added dialog for teaching Pokemon new moves

- src/components/equations/ItemEffects.ts
> Added PP functionality

- src/components/equations/ItemEffects.ts
> Added logic for adding battle stats

- src/FullScreenPokemon.ts
- src/components/MoveAdder.test.ts
- src/components/MoveAdder.ts
Fixed #634. I ended up forking again, so this is a new PR.
I still need to fix some things, so don't look at this yet.
> Added a unit test for the new move API

- src/components/MoveAdder.test.ts
> Nitpicked MoveAdder.test.ts

- package.json
- src/components/cutscenes/PokeCenterCutscene.test.ts
- src/components/cutscenes/PokeCenterCutscene.ts
- src/components/things/ThingNames.ts
- src/fakes.test.ts
Made menus use menugraphr@0.7.7's new `finishLinesAutomatically` for fewer manual clock ticks.
> Streamlined PokeCenter tests

- src/components/Cutscenes.ts
- src/components/Menus.ts
- src/components/cutscenes/ComputerCutscene.ts
- src/components/maps/Macros.ts
- src/components/menus/Computer.test.ts
- src/components/menus/Computer.ts
- src/components/menus/computer/ComputerStorage.ts
- src/components/things/ThingNames.ts
- src/creators/createMenuGrapher.ts
- src/creators/createScenePlayer.ts
Adds the first menu and Bill's with closing. Nothing else.
Starts on #689.
> Started on PokeCenter computers

- src/components/battles/animations/shared/moves/moves/Scratch.ts
Fixes #691 and causes the animation to play correctly.
> fixing scratch bug

- src/components/battles/animations/shared/Moves.ts
This fix will allow all current move animations in game to be played.
> Allows move animations to play

- src/components/Battles.ts
- src/components/battles/animations/Starting.ts
Fixes the issues @Phansa discovered with asynchronous code launching battle starts.
> Removed async operations from starting battles

- src/components/battles/animations/shared/moves/MovesBag.ts
- src/components/battles/animations/shared/moves/moves/PayDay.ts
- src/components/constants/Moves.ts
Adds the payday move/animation using a bubble object for now.
> Adds Pay Day animation to the game

- src/components/battles/animations/shared/moves/MovesBag.ts
- src/components/battles/animations/shared/moves/moves/PoisonSting.ts
- src/components/constants/Moves.ts
Adds the poison sting move animation to the game.
> Adds Poison Sting to the game

- src/interface/CreateInterface.ts
- src/interface/InterfaceSettings.test.ts
- src/interface/InterfaceSettings.ts
Simplifies the unnecessary class for creating UI settings to be a standalone arrow function. Adds a couple of unit tests too.
Fixes #611.
> Un-inversed speed set through the UI

- src/components/Actions.ts
- src/components/Things.ts
- src/components/actions/Roaming.test.ts
- src/components/actions/Roaming.ts
- src/components/things/ThingNames.ts
- tslint.json
Adds a tracking member to roaming characters underneath a new `IRoamingCharacter` interface.
Fixes #814.
> Limited roaming distances to 3 in any direction

- src/components/Inputs.ts
> Always prevent default on input events

- src/components/Things.ts
> Stopped adding .bordering on Scenery, Terrain
